### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by tirolo** [SharpeRAD/Cake.Powershell#12] opened 2016-10-16 03:33 UTC
First of all big thanks for the extension, it's awesome!

I was just wondering as PS and cake are cross platform it would be great to make this addin work cross platform as well (or maybe it is and I'm missing something?). I have absolutely no idea where to start on this one but would be more than happy to give a hand.

I tried running it on my mac and this is the output:
![image](https://cloud.githubusercontent.com/assets/4400097/19415022/6d6f78c6-9359-11e6-9984-2b614393be7c.png)

Ideas?

**Comment by SharpeRAD** [comment] 2016-10-16 09:05
Haven't looked into it but it would be cool if it was cross platform 😉 

I think the issue is going to be with "System.Management.Automation.dll" and its dependency chain, I know Powershell is on [Github ](https://github.com/powershell) now so that's probably the best place to start.

**Comment by lprichar** [comment] 2018-10-16 22:02
It might be nice to at least give a "not supported on this platform" kind of error, I spent a while trying to figure this out.  Here's the SEO friendly version of the error btw:

````
Error: System.AggregateException: One or more errors occurred. ---> 
System.InvalidProgramException: Invalid IL code in 
System.Management.Automation.Runspaces.RunspaceFactory:CreateRunspace 
(System.Management.Automation.Host.PSHost)
````

**Comment by SharpeRAD** [comment] 2018-10-17 07:35
I'm not convinced that's the responsibility of the add-in. The issue has remained open and is obviously easily to find, so the most constructive thing I can do is add a "up-for-grabs" label in the hope that someone will find the time to make this add-in cross platform.

**Comment by SharpeRAD** [comment] 2018-10-31 18:46
I've Merged a PR for partial Linux support but will leave this open in case anyone wants to explore full cross platform support in the future.

**Comment by AdaskoTheBeAsT** [comment] 2021-02-21 19:33
Done in https://github.com/SharpeRAD/Cake.Powershell/pull/83
please review

**Closed** 2021-02-25 18:52 UTC
Labels: up-for-grabs
